# Generated by Django 3.0.5 on 2020-04-11 14:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=280)),
                ('where', models.CharField(max_length=140)),
                ('when', models.DateField()),
                ('duration', models.IntegerField(default=1)),
                ('approved', models.BooleanField(default=False)),
                ('approved_updated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
